language: r
sudo: required
install_r:
  - devtools
script:
  - Rscript -e 'devtools::install_github("csgillespie/benchmarkme-data")'
  - Rscript -e 'devtools::install_github("csgillespie/benchmarkme")'
  - Rscript -e 'devtools::install_github("rstudio/bookdown")'
  - Rscript -e 'bookdown::render_book("index.Rmd")'
after_success:
  - BASE_REPO=$PWD
  - cd ..; mkdir gh-pages; cd gh-pages
  - git init
  - git config user.name "Colin Gillespie"
  - git config user.email "csgillespie@gmail.com"
  - git config --global push.default simple
  - git remote add upstream "https://$GH_TOKEN@github.com/csgillespie/efficientR.git"
  - git fetch upstream 2>err.txt
  - git checkout gh-pages
  - cp -fvr $BASE_REPO/*html $BASE_REPO/libs/ $BASE_REPO/figures/ style.css .
  - git add *.html; git add libs/; git add figures/; git add style.css
  - git commit -a -m "Updating book"
  - git status
  - git push
after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    secure: Y1Qr5n9XgEb2yDv+rJ3+OxWSu+oRulPaSQvSvgsMDRSNOpEejFSyzxxtM/1k8t0OtmiHCjvhgaq00lU0ZpHHdycDO30EGKprA+dt/TAOUpkAnbZtXBYAqvcbitUrcR6YtDRSpJfwmM89Kq/vsPmc9bA93N2Lc0w19H0zUxhL0xExNvPQ5nHllLgPyJgik2qVeESxHqNhfKBXIsd42YZCkfpby5AM+nlxRo70i6ZY2W5Ow7X3WH6RNkt9F3mIODl+9X2qFNI3JoAqZUZal/UkUlXmtnUZ7qeuHff9IHkHQ1Iq5cRY3F7w+gGg2o+wDuDWa898ZEHpj8rOw4BQ0HvESlljAFPWtI4lUqHKy5EqpIR9bLO3h4TtgLI1FuTmEcwtxtq4QKizQD8KOnb9VEI6lO2F0Gg8E4836QkYBmumrk8u7wBtoSZ+znCkfeuo4TdAUgyI89VQGX/TMNV1jZP1CzcvLXq24ZfdAIXY/I4cEdy8dAEDbhwEKQ40ECHT84G35TRbeV89PbW3RdyNTmeIa50HQg4d/p+ktdCN+mqfDAYSDluU+rVeUF6SDyYi5SxedqriNTvb7wi5CQoJwtwcTa7zRd5+8b5C1NUWzXWt9sXhpIRiQz/Bzmhfm0bIkJhIRuyNZD5nU5nVNlsqanZwjrFtFSCJFAVDJK1MPv8q6P8=
